# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171205_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('behavior', models.IntegerField()),
                ('effort', models.IntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enrollment', unique_for_date='date')),
            ],
            options={
                'ordering': ('enrollment', 'date'),
            },
        ),
    ]
