# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='api.Enrollment', unique_for_date='date'),
        ),
    ]
