# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171129_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
